In [201]:
#Task 1
my_file = open("numbers_file.txt","w")
data1 =input("Tell me 4 numbers ?")
my_file.write(data1)
my_file.close()

In [ ]:
#Task 1
my_file = open("numbers_file.txt","w")
data1 =input(int("Tell me 4 numbers ?"))
my_file.write(data1)
my_file.close()



#Task 2
student_mark = int(input("What is you mark? "))

def mark_student(student_mark):

  if student_mark <=50:
    print("Your grade is:D")
  elif student_mark >50 and student_mark <=65:
    print("Your grade is:C")
  elif student_mark >65 and student_mark <=77:
    print("Your grade is:", "B")
  else:
    print("Your grade is:A")
  return
mark_student(student_mark)
# Extension Task 2
target_mark = int(input("What is you target mark? "))
student_name = input("what is your name ?")
if student_mark < target_mark:
  print("Keep going", student_name + ",your nearly at your target grade")
elif student_mark == target_mark:
  print("Congratualations", student_name+ " you have met your target grade !")
else:
  print(student_name, "Your above target great job")

In [1]:
import numpy as np

In [11]:
q1 = np.arange(10)

print(q1)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
q2 = np.ones((3,3), dtype=bool)
print(q2)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [23]:
#Q3 - Extract all odd numbers from array of 1-10

q3 = np.arange(1,11)
print(q3)

print(q3[0:11:2])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [104]:
q4 = np.arange(1,11)
print(q4)
second_q4 =np.arange(1,11)
second_q4[second_q4%2 == 1] =-1
print(second_q4)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [49]:
q5 = np.arange(0,60,5)
print(q5)

amended_q5 = q5.reshape(2,6)
print("q5 is now :",amended_q5)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
q5 is now : [[ 0  5 10 15 20 25]
 [30 35 40 45 50 55]]


In [114]:
#Create two arrayss a and b, stack these arrays vertically use the np.dot and np.sum to calculate totals

import numpy as np
aa = np.array([[2,4,4],[8,12,9],[9,3,1]])
bb= np.array([[1,3,7],[9,11,8],[1,4,6]])

#print(aa)
#print(bb)

ab =np.vstack([aa,bb])
print(ab)

c = np.dot(aa ,bb)
print(c)

sum = np.sum(c)
sum1 = np.sum( ab)
print("Sum of Dot is :",sum)
print("Sum of arrays is:", sum1)

[[ 2  4  4]
 [ 8 12  9]
 [ 9  3  1]
 [ 1  3  7]
 [ 9 11  8]
 [ 1  4  6]]
[[ 42  66  70]
 [125 192 206]
 [ 37  64  93]]
Sum of Dot is : 895
Sum of arrays is: 102


In [183]:
#Extension 1

repeat =np.arange(1,4)
new = np.kron(repeat, np.ones((1,3)))
b = np.arange(1,4,1)
b2 = np.tile(b,3)
final = np.concatenate((new2, b2))
print(final)

[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


In [193]:
#Extention 2

a = np.arange(1,6)
b = np.arange(4,10)

print(a)
print(b)
b[a[np.searchsorted(a,b)]!= b]


[1 2 3 4 5]
[4 5 6 7 8 9]


IndexError: index 5 is out of bounds for axis 0 with size 5