In [1]:
import numpy as np

In [2]:
a = np.zeros(8)

print(a)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print(a + 5)



[5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
sum = np.sum(a)
print(sum)

0.0


In [11]:
q1 = np.arange(10)

print(q1)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
q2 = np.ones((3,3), dtype=bool)
print(q2)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [23]:
#Q3 - Extract all odd numbers from array of 1-10

q3 = np.arange(1,11)
print(q3)

print(q3[0:11:2])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [104]:
q4 = np.arange(1,11)
print(q4)
second_q4 =np.arange(1,11)
second_q4[second_q4%2 == 1] =-1
print(second_q4)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [49]:
q5 = np.arange(0,60,5)
print(q5)

amended_q5 = q5.reshape(2,6)
print("q5 is now :",amended_q5)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
q5 is now : [[ 0  5 10 15 20 25]
 [30 35 40 45 50 55]]


In [114]:
#Create two arrayss a and b, stack these arrays vertically use the np.dot and np.sum to calculate totals

import numpy as np
aa = np.array([[2,4,4],[8,12,9],[9,3,1]])
bb= np.array([[1,3,7],[9,11,8],[1,4,6]])

#print(aa)
#print(bb)

ab =np.vstack([aa,bb])
print(ab)

c = np.dot(aa ,bb)
print(c)

sum = np.sum(c)
sum1 = np.sum( ab)
print("Sum of Dot is :",sum)
print("Sum of arrays is:", sum1)

[[ 2  4  4]
 [ 8 12  9]
 [ 9  3  1]
 [ 1  3  7]
 [ 9 11  8]
 [ 1  4  6]]
[[ 42  66  70]
 [125 192 206]
 [ 37  64  93]]
Sum of Dot is : 895
Sum of arrays is: 102
